name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows the workflow to push changes
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@master
        with:
          github_user_name: drmisssciurus # Replace with your GitHub username
          svg_out_path: dist/snake.svg

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Snake Game"
          file_pattern: dist/snake.svg
