name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Generate Snake Game
        uses: Platane/snk@master
        with:
          github_user_name: drmisssciurus # Replace with your GitHub username
          svg_out_path: dist/snake.svg

      - name: Push the updated snake.svg
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/snake.svg"
          message: "Updated snake game"
